import { EpochSeconds, Integer } from "@/api-schema/common-types";
import { fromStructure, Schema, Selection, Structure } from "@/api-schema/schema.types";

const statsStructure: Structure = {
    id: "stats",
    name: "Stats",
    schema: {
        timestamp: { type: EpochSeconds },
        users_total: { type: Integer },
        users_male: { type: Integer },
        users_female: { type: Integer },
        users_enby: { type: Integer },
        users_marriedcouples: { type: Integer },
        users_daily: { type: Integer },
        total_users_logins: { type: Integer },
        total_users_playtime: { type: Integer },
        job_army: { type: Integer },
        job_grocer: { type: Integer },
        job_medical: { type: Integer },
        job_casino: { type: Integer },
        job_education: { type: Integer },
        job_law: { type: Integer },
        job_company: { type: Integer },
        job_none: { type: Integer },
        crimes: { type: Integer },
        jailed: { type: Integer },
        money_onhand: { type: Integer },
        money_citybank: { type: Integer },
        items: { type: Integer },
        events: { type: Integer },
        wars_ranked: { type: Integer },
        wars_territory: { type: Integer },
        wars_raid: { type: Integer },
        communication_events: { type: Integer },
        communication_totalevents: { type: Integer },
        communication_messages: { type: Integer },
        communication_totalmessages: { type: Integer },
        communication_chats: { type: Integer },
        communication_forumposts: { type: Integer },
        communication_articles: { type: Integer },
        communication_articleviews: { type: Integer },
        communication_articlereads: { type: Integer },
        forums_posts: { type: Integer },
        forums_threads: { type: Integer },
        forums_likes: { type: Integer },
        forums_dislikes: { type: Integer },
        crimes_today: { type: Integer },
        gym_trains: { type: Integer },
        points_total: { type: Integer },
        points_market: { type: Integer },
        points_averagecost: { type: Integer },
        points_bought: { type: Integer },
        total_points_boughttotal: { type: Integer },
        total_attacks_won: { type: Integer },
        total_attacks_lost: { type: Integer },
        total_attacks_stalemated: { type: Integer },
        total_attacks_runaway: { type: Integer },
        total_attacks_hits: { type: Integer },
        total_attacks_misses: { type: Integer },
        total_attacks_criticalhits: { type: Integer },
        total_attacks_roundsfired: { type: Integer },
        total_attacks_stealthed: { type: Integer },
        total_attacks_moneymugged: { type: Integer },
        total_attacks_respectgained: { type: Integer },
        total_items_marketbought: { type: Integer },
        total_items_bazaarbought: { type: Integer },
        total_items_auctionswon: { type: Integer },
        total_items_sent: { type: Integer },
        total_trades: { type: Integer },
        total_items_bazaarincome: { type: Integer },
        total_items_cityfinds: { type: Integer },
        total_items_dumpfinds: { type: Integer },
        total_items_dumped: { type: Integer },
        total_jail_jailed: { type: Integer },
        total_jail_busted: { type: Integer },
        total_jail_busts: { type: Integer },
        total_jail_bailed: { type: Integer },
        total_jail_bailcosts: { type: Integer },
        total_hospital_trips: { type: Integer },
        total_hospital_medicalitemsused: { type: Integer },
        total_hospital_revived: { type: Integer },
        total_mails_sent: { type: Integer },
        total_mails_sent_friends: { type: Integer },
        total_mails_sent_faction: { type: Integer },
        total_mails_sent_company: { type: Integer },
        total_mails_sent_spouse: { type: Integer },
        total_classifiedads_placed: { type: Integer },
        total_bounty_placed: { type: Integer },
        total_bounty_rewards: { type: Integer },
        total_travel_all: { type: Integer },
        total_travel_argentina: { type: Integer },
        total_travel_mexico: { type: Integer },
        total_travel_dubai: { type: Integer },
        total_travel_hawaii: { type: Integer },
        total_travel_japan: { type: Integer },
        total_travel_unitedkingdom: { type: Integer },
        total_travel_southafrica: { type: Integer },
        total_travel_switzerland: { type: Integer },
        total_travel_china: { type: Integer },
        total_travel_canada: { type: Integer },
        total_travel_caymanislands: { type: Integer },
        total_drugs_used: { type: Integer },
        total_drugs_overdosed: { type: Integer },
        total_drugs_cannabis: { type: Integer },
        total_drugs_ecstacy: { type: Integer },
        total_drugs_ketamine: { type: Integer },
        total_drugs_lsd: { type: Integer },
        total_drugs_opium: { type: Integer },
        total_drugs_shrooms: { type: Integer },
        total_drugs_speed: { type: Integer },
        total_drugs_pcp: { type: Integer },
        total_drugs_xanax: { type: Integer },
        total_drugs_vicodin: { type: Integer },
        total_merits_bought: { type: Integer },
        total_refills_bought: { type: Integer },
        total_company_trains: { type: Integer },
        total_statenhancers_used: { type: Integer },
    },
};
const structures = [statsStructure];

const schema: Schema = {
    stats: fromStructure(statsStructure),
};

const StatsSelection: Selection = {
    name: "stats",
    description: "Some stats on Torn.",
    access: "public",
    schema,
    structures,
    id: {
        optional: false,
    },
};

export default StatsSelection;
